### ISSUE TITLE
System requirements (GPU?)

### ISSUE THREAD

**Issue by DanielTakeshi** [isl-org/lang-seg#1]
Hello,

This is great work @Boyiliee ! I'm excited to try this out.

I have a quick question: what kind of system requirements are necessary to train and run inference on this model? Specifically I am wondering about the type of GPU(s) needed to train LSeg.

**Comment by Boyiliee** [comment]
Hi @DanielTakeshi, thanks for your interest in LSeg!

For training, we typically use V100, but I assume others would also work if the memory is allowed.

For inference, both GPU/CPU work. If you want to use CPU, for example, you can follow https://github.com/isl-org/lang-seg/blob/main/lseg_app.py#L314. And of course, you can modify based on your machine and requirements.

Hope this helps!

Best,
Boyi

**Comment by DanielTakeshi** [comment]
Thanks! Right now I have some machines with GPUs that have 12 GB of RAM each available, I wonder if that might not be enough memory (assuming we use 1 GPU). However I guess I just have to try the code to see if it work and maybe reduce batch sizes if there are errors.

**Comment by Boyiliee** [comment]
If you try the demo or inference test, I guess it should work!

But for training, we also provide different options for different model backbone implementation, for example,`--backbone clip_vitb32_384`, details in https://github.com/isl-org/lang-seg/blob/main/modules/models/lseg_net.py#L119. While I guess for 12GB, you might need to revise a little bit to reduce the model size for training ;)

Hope this helps! And please let me know if there are any other questions!
