### ISSUE TITLE
Error when running test.py

### ISSUE THREAD

**Issue by Sun-XH** [isl-org/lang-seg#10]
Hi! Thanks for the good work!
I met a problem when I tried to run test.sh. The error said, "cannot import name 'Resize' from 'utils'". I have checked utils.py, there is no function or class called 'Resize'. Is the code missing this part? 
Looking forward to your reply.

**Comment by Boyiliee** [comment]
Hi @Sun-XH,

Thanks for your interest in LSeg and thanks for pointing this out!

Just updated the file. Hope this helps.

Best wishes for your research!

Best,
Boyi
