### ISSUE TITLE
freeze CLIP TextEncoder

### ISSUE THREAD

**Issue by Ahnsun** [isl-org/lang-seg#11]
Hi, the paper pointed out that we should freeze the text encoder of CLIP during training. I wonder how to achieve it and where is the corrresponding code. Thanks!

**Comment by soskek** [comment]
In my understanding (though I'm not an author), the optimizer selects which parameters to be updated.
https://github.com/isl-org/lang-seg/blob/main/modules/lsegmentation_module.py#L119-L175
Because these lines do not select CLIP parameters (`self.net.clip_pretrained`), they are frozen.

**Comment by Boyiliee** [comment]
Thanks @soskek for answering this!

Best wishes for your research! @Ahnsun
