### ISSUE TITLE
multiple-gpu

### ISSUE THREAD

**Issue by Feobi1999** [isl-org/lang-seg#15]
If I use eight GPUS, in addition to modifying the batch size=8, do I need to modify other parameters such as --num_nodes and lr?

**Comment by Boyiliee** [comment]
Hi, @Feobi1999,

You don't need to modify other parameters. Also, we highly recommend you could take the look at the instructions of [PytorchLightning](https://github.com/PyTorchLightning/pytorch-lightning) and [DPT](https://github.com/isl-org/DPT), you don't need to modify the batch size as well.

Hope this helps!
