### ISSUE TITLE
question about the image encoder

### ISSUE THREAD

**Issue by chufengt** [isl-org/lang-seg#20]
Hi, thanks for open-sourcing the code.

I have a quick question:

What's the reason for choosing DPT as the image encoder?

What should I note if I want to use other encoders (e.g., HR-Net)?

**Comment by Boyiliee** [comment]
Hi, @chufengt,

When we design LSeg, DPT is one of the state-of-the-art models for semantic segmentation. Therefore, we pick it for our architecture.

Yea, you could use other encoders, but you may change the hyperparameters based on their settings.

Hope this helps!

**Comment by ngfuong** [comment]
Hi I have a follow-up question about DPT as image encoder,

![image](https://user-images.githubusercontent.com/53037851/189049772-9d1f623b-a3c6-4e9b-a341-992f031eff0d.png)
According to the **Training Details** section in your paper, did you use DPT as both the encoder and decoder?
Where in the code can I find your implementation of DPT?
