### ISSUE TITLE
Test_lseg_zs.py 

### ISSUE THREAD

**Issue by Ehteshamciitwah** [isl-org/lang-seg#23]
Thank you for providing an implementation. While testing the code, I am running the Test_lseg_zs.py  file for pascal, but facing an error.
Any suggestion?
![image](https://user-images.githubusercontent.com/79190474/180155480-b9898f04-9a3b-4d19-a6cb-6756c548c4da.png)

**Comment by Boyiliee** [comment]
Hi @Ehteshamciitwah,

Thanks for your interest in LSeg!

I haven't met this issue, but guess it is because of the [installation](https://github.com/isl-org/lang-seg#installation).

Hope this helps.

Best,
Boyi
