### ISSUE TITLE
Error when building Pytorch-encoding

### ISSUE THREAD

**Issue by StarsTesla** [isl-org/lang-seg#27]
Hi, I would like to tried your code, but the error shows up when I tried to install the pytorch-encoding. Could you give us your environment info of CUDA GPU python g++ and so on？Do you have any advice about installing it，which I see a lot of people get the error.

My env:
OS: Ubuntu 18.04
gcc: 7.5.0
GPU:3090
driver：515
CUDA: tried 11.7 and 10.2
pytorch: tried 1.12 and 1.7.1

**Comment by shan23chen** [comment]
same here

**Comment by Boyiliee** [comment]
Thanks @shan23chen @StarsTesla for your interest in LSeg!

You can find all the details at https://github.com/isl-org/lang-seg/blob/main/requirements.txt#L103.

Alternatively, you could use Option 2 to install all the packages.

Hope this helps.

**Comment by StarsTesla** [comment]
well, I can install the torch-encoding, but I cannot run the notebook.

logs shows:
`ImportError: /root/anaconda3/envs/LSeg/lib/python3.8/site-packages/encoding/cpu.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexIfEEEEPKNS_6detail12TypeMetaDataEv`


 Could you inform us more of the CUDA version , python version and etc. of your runtime env. And BTW, some packages from the requirement's version are different from the option 2, for example, the torch version. 

Besides, the pytorch-lightning version is also shows a error of:
`pl.metrics`

I have change the code to

```
import torchmetrics
self.train_accuracy = torchmetrics.Accuracy()
```
Then seems fine, But still got the error logs above.
Really appreciate it！
