### ISSUE TITLE
Whether the training is going on normally

### ISSUE THREAD

**Issue by qliu520** [isl-org/lang-seg#28]
When I train the code, the multi-GPU allocation stops at the following location：
"
Resuming checkpoint None, exp_version=None
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/5
Resuming checkpoint None, exp_version=None
initializing ddp: GLOBAL_RANK: 4, MEMBER: 5/5

"
Is this training?  Or something wrong ？

**Comment by Boyiliee** [comment]
Hi @qliu520 ,

Thanks for your interest in LSeg!

It seems that you are not loading all the GPUs, you might need to check you machine and system.

Hope this helps.

Best,
Boyi
