### ISSUE TITLE
How long does it takes for default training?

### ISSUE THREAD

**Issue by synsin0** [isl-org/lang-seg#31]
System: 4xRTX3090.
Training scripts: Default training scripts:
python -u train_lseg.py --dataset ade20k --data_path ./datasets --batch_size 1 --exp_name lseg_ade20k_l16 \
--base_lr 0.004 --weight_decay 1e-4 --no-scaleinv --max_epochs 200 --widehead --accumulate_grad_batches 2 --backbone clip_vitl16_384

My system has shown that one epoch takes for 45mins, which is a pretty long time for 200 epochs. Is that a normal procedure? Or we may not need max epochs like that?

**Comment by Boyiliee** [comment]
Hi @synsin0 ,

Thanks for your interest in LSeg!

As has been mentioned, we used 8 V100 and trained for 200 epochs. I guess, it is because of your batchsize=1, we use batchsize = 4 instead.

Hope this helps.

Best,
Boyi
