### ISSUE TITLE
i have a question about  text feature dimention

### ISSUE THREAD

**Issue by senlin-ali** [isl-org/lang-seg#35]
hi、i saw the paper that text feature dim is N 、but N is not sure  in different image ,   so how can we  design the Spatial regularization Structure at the back

**Comment by Boyiliee** [comment]
Hi @senlin-ali ,

Thanks for your interest in LSeg!

The N doesn't mean the dimension of image but image features, you could change the dimension based on your design.

Hope this helps!

Best,
Boyi
