### ISSUE TITLE
Model parameter descriptions

### ISSUE THREAD

**Issue by jonathan-roberts1** [isl-org/lang-seg#37]
Hi Boyi,

Thanks a lot for releasing the code for LSeg! 

I’ve been having a play around using the demo code + model in a zero-shot setting and just have a few (hopefully quick) questions about some of the model parameters.

Could you please give a brief overview (description, where the default values originate, what the optimum values might be) of the following parameters used in the LSeg_MultiEvalModule:
    1. ‘scales’  - e.g., lseg_app.py Line 315
    2. (‘base_size’ - e.g., additional_utils/models.py Line 28)
    3. ‘crop_size’ - e.g., additional_utils/models.py Line 29
And this parameter used in the LSegNet class:
    5. scale_factor - e.g., module/models/lseg_net.py Line 216 (this has a default value of 0.5 and is different to the scale_factor parameter that is passed to 'Interpolate')

Thanks!

**Comment by Boyiliee** [comment]
Hi @jonathan-roberts1 ,

Thanks for your interest in LSeg!

Regarding the parameters, all these factors keep the same policy with [DPT](https://github.com/isl-org/DPT) for the semantic segmentation settings.

Hope this helps!

Best,
Boyi
