### ISSUE TITLE
RuntimeError: Trying to backward through the graph a second time

### ISSUE THREAD

**Issue by zhengyuan-xie** [isl-org/lang-seg#38]
Hi
Thanks for your great work! When I tried to add LSegNet into my own framework, there was a RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. My train function is(run on ADE20K):

```
def train(self, cur_epoch, optim, train_loader, scheduler=None, print_int=10, logger=None):
        device = self.device
        model = self.model
        criterion = nn.CrossEntropyLoss(ignore_index=-1)
        model.train()
        for cur_step, (images, labels) in enumerate(train_loader):
            images = images.to(device, dtype=torch.float32)
            labels = labels.to(device, dtype=torch.long)
            optim.zero_grad()
            outputs = model(images, labelset='')
            loss = criterion(outputs, labels)
            self.scaler.scale(loss)
            loss.backward()
            optim.step()
            if scheduler is not None:
                scheduler.step()
```
The model is LSegNet and I didn't modify lseg_net.py. I think maybe some optimizations have been made by Pytorch-lighting.  Could you give me some suggestions? Thank you!

**Comment by zhengyuan-xie** [comment]
And when I was running official code, If num_sanity_val_steps was set to 0, then the same error was reported.

**Comment by Boyiliee** [comment]
Hi @zhengyuan-xie ，

Thanks for your interest in LSeg!

You should be able to find a detailed explanation [here](https://discuss.pytorch.org/t/runtimeerror-trying-to-backward-through-the-graph-a-second-time-but-the-buffers-have-already-been-freed-specify-retain-graph-true-when-calling-backward-the-first-time/6795).

Hope this helps!

Best,
Boyi
