### ISSUE TITLE
Query regarding the Dataset Split

### ISSUE THREAD

**Issue by anonyn498** [isl-org/lang-seg#4]
Hi , 

Thanks for open sourcing this awesome work. While going through your code I could not find the zero-shot or few-shot splits for the dataset. I could only find the ADE20K supervised label split. Does this mean this code is for the fully supervised version ?

**Comment by Boyiliee** [comment]
Hi, @anonyn498 ,

Thanks for your interest in LSeg!

For the current version, we give an example about how to use LSeg for training, testing and demo. We release the code regarding the fully supervised experiments (ablation studies) in comparison with the previous pure vision model without text assistance. See Table 4, 5, 6 of the paper.

For zero-shot and few-shot split, we strictly follow the rule from [HSNet](https://github.com/juhongm999/hsnet), you could follow it to check the detailed splits and replace the label set based on your experimental requirements as well.

More will be updated.

Hope this helps!
