### ISSUE TITLE
Training configuration

### ISSUE THREAD

**Issue by XAVILLA** [isl-org/lang-seg#7]
Hi! Can you please let me know what is the correct training configuration to reproduce the performance reported in the paper?

In the paper you mentioned that 6 GPUs were used and batch size was set to 6. Does this mean that I should just launch train.sh with 6 GPUs available? And can you please let me know what is the approximate time for training? Thanks!

**Comment by XAVILLA** [comment]
When using 6gpus it seems to take 1h per epoch. Is this expected?

**Comment by Boyiliee** [comment]
Hi, @XAVILLA ,

1) We have provided a training example in README.MD. Please check it for details.  
2) It depends on your machine. Any number of GPUs should work. It also depends on the task (dataset) for each epoch.
3) If you train ADE20k, 1-2days for all in general, but it totally depends on what kind of machine you use.

Hope this helps!
